import { Badge } from '@/types/gamification';

export const ALL_CIVIC_BADGES: Badge[] = [
  // ==========================================
  // 1. 🌱 ONBOARDING & NOVICE (6 BADGES)
  // ==========================================
  {
    id: 'first_step',
    title: 'First Step',
    description: 'Submitted your first roadway hazard report with on-site evidence.',
    icon: 'first_step',
    category: 'onboarding',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Novice Scout',
  },
  {
    id: 'sharp_eye',
    title: 'Sharp Eye',
    description: 'Uploaded your first clear high-resolution photo evidence.',
    icon: 'sharp_eye',
    category: 'onboarding',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Visual Spotter',
  },
  {
    id: 'first_verifier',
    title: 'On-Site Verifier',
    description: 'Confirmed your first active hazard on-site to assist community safety.',
    icon: 'first_verifier',
    category: 'onboarding',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Field Verifier',
  },
  {
    id: 'ready_scout',
    title: 'Profile Pioneer',
    description: 'Configured your custom scout profile and privacy preferences.',
    icon: 'ready_scout',
    category: 'onboarding',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Certified Scout',
  },
  {
    id: 'location_scout',
    title: 'GPS Navigator',
    description: 'Submitted a report with high-accuracy GPS satellite lock.',
    icon: 'location_scout',
    category: 'onboarding',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Pinpoint Scout',
  },
  {
    id: 'quick_responder',
    title: 'Quick Responder',
    description: 'Verified a new hazard report within its first hour of discovery.',
    icon: 'quick_responder',
    category: 'onboarding',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Rapid Scout',
  },

  // ==========================================
  // 2. 🕳️ POTHOLE & ROAD SPECIALISTS (8 BADGES)
  // ==========================================
  {
    id: 'pothole_novice',
    title: 'Crater Spotter',
    description: 'Reported your first asphalt pothole hazard.',
    icon: 'pothole_novice',
    category: 'potholes',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Crater Spotter',
  },
  {
    id: 'pothole_patrol',
    title: 'Pothole Patrol',
    description: 'Reported 5 road potholes to safeguard two-wheelers and drivers.',
    icon: 'pothole_patrol',
    category: 'potholes',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Pothole Ranger',
  },
  {
    id: 'pothole_hunter',
    title: 'Asphalt Warden',
    description: 'Logged 15 pothole hazards across high-traffic city corridors.',
    icon: 'pothole_hunter',
    category: 'potholes',
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Asphalt Warden',
  },
  {
    id: 'pothole_master',
    title: 'Pothole Master',
    description: 'Flagged 30 major road craters protecting commuters from damage.',
    icon: 'pothole_master',
    category: 'potholes',
    requiredCount: 30,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Pothole Master',
  },
  {
    id: 'pothole_legend',
    title: 'Highway Vanguard',
    description: 'Legendary achievement: 50 pothole submissions logged.',
    icon: 'pothole_legend',
    category: 'potholes',
    requiredCount: 50,
    currentCount: 0,
    isUnlocked: false,
    tier: 'master',
    rewardTitle: 'Highway Vanguard',
  },
  {
    id: 'road_doctor_1',
    title: 'Surface Medic',
    description: 'Reported 5 severe road surface cracks or structural failures.',
    icon: 'road_doctor_1',
    category: 'potholes',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Surface Medic',
  },
  {
    id: 'road_doctor_2',
    title: 'Pavement Surgeon',
    description: 'Logged 20 dangerous pavement collapses and structural road ruts.',
    icon: 'road_doctor_2',
    category: 'potholes',
    requiredCount: 20,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Pavement Surgeon',
  },
  {
    id: 'road_doctor_3',
    title: 'Infrastructure Titan',
    description: 'Documented 50 structural road and bridge surface hazards.',
    icon: 'road_doctor_3',
    category: 'potholes',
    requiredCount: 50,
    currentCount: 0,
    isUnlocked: false,
    tier: 'diamond',
    rewardTitle: 'Infrastructure Titan',
  },

  // ==========================================
  // 3. 💡 LIGHTING & NIGHT OPS (6 BADGES)
  // ==========================================
  {
    id: 'lamp_spotter',
    title: 'Spark Scout',
    description: 'Reported your first unlit or broken street lamp.',
    icon: 'lamp_spotter',
    category: 'lighting',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Spark Scout',
  },
  {
    id: 'night_watch_1',
    title: 'Night Watch',
    description: 'Flagged 5 dark zones and broken streetlights to keep streets safe.',
    icon: 'night_watch_1',
    category: 'lighting',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Night Watchman',
  },
  {
    id: 'night_watch_2',
    title: 'Luminary Sentinel',
    description: 'Reported 15 malfunctioning public streetlamps across neighborhoods.',
    icon: 'night_watch_2',
    category: 'lighting',
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Luminary Sentinel',
  },
  {
    id: 'night_watch_3',
    title: 'Beacon Master',
    description: 'Logged 30 lighting blackouts helping illuminate public transit routes.',
    icon: 'night_watch_3',
    category: 'lighting',
    requiredCount: 30,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Beacon Master',
  },
  {
    id: 'midnight_owl',
    title: 'Midnight Owl',
    description: 'Logged an active hazard report during late night hours (10 PM - 5 AM).',
    icon: 'midnight_owl',
    category: 'lighting',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Midnight Scout',
  },
  {
    id: 'dawn_patrol',
    title: 'Dawn Patrol',
    description: 'Logged an early morning roadway hazard during dawn (5 AM - 7 AM).',
    icon: 'dawn_patrol',
    category: 'lighting',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Dawn Scout',
  },

  // ==========================================
  // 4. ♻️ WASTE & CLEANLINESS (6 BADGES)
  // ==========================================
  {
    id: 'eco_starter',
    title: 'Trash Tracker',
    description: 'Reported your first roadside garbage pile or bin overflow.',
    icon: 'eco_starter',
    category: 'waste',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Trash Tracker',
  },
  {
    id: 'eco_warrior',
    title: 'Eco Warrior',
    description: 'Flagged 5 public waste accumulation hotspots.',
    icon: 'eco_warrior',
    category: 'waste',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Eco Warrior',
  },
  {
    id: 'eco_sentinel',
    title: 'Clean City Sentinel',
    description: 'Documented 15 garbage overflow points for municipal pickup.',
    icon: 'eco_sentinel',
    category: 'waste',
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Clean City Sentinel',
  },
  {
    id: 'eco_champion',
    title: 'Green Guardian',
    description: 'Logged 30 environmental waste hazards across your district.',
    icon: 'eco_champion',
    category: 'waste',
    requiredCount: 30,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Green Guardian',
  },
  {
    id: 'eco_legend',
    title: 'Zero Waste Legend',
    description: 'Documented 50 neighborhood sanitation and waste overflow sites.',
    icon: 'eco_legend',
    category: 'waste',
    requiredCount: 50,
    currentCount: 0,
    isUnlocked: false,
    tier: 'diamond',
    rewardTitle: 'Zero Waste Legend',
  },
  {
    id: 'speedy_cleaner',
    title: 'Rapid Clean Reporter',
    description: 'Logged 3 waste hotspots in a single day.',
    icon: 'speedy_cleaner',
    category: 'waste',
    requiredCount: 3,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Rapid Clean Reporter',
  },

  // ==========================================
  // 5. 🛡️ COMMUNITY VERIFICATIONS (8 BADGES)
  // ==========================================
  {
    id: 'verify_bronze',
    title: 'Field Inspector',
    description: 'Verified 5 community hazard reports on-site.',
    icon: 'verify_bronze',
    category: 'verification',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Field Inspector',
  },
  {
    id: 'verify_silver',
    title: 'District Scout',
    description: 'Verified 15 roadway issues confirming ongoing hazards.',
    icon: 'verify_silver',
    category: 'verification',
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'District Scout',
  },
  {
    id: 'verify_gold',
    title: 'Chief Inspector',
    description: 'Performed 30 on-site citizen verifications.',
    icon: 'verify_gold',
    category: 'verification',
    requiredCount: 30,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Chief Inspector',
  },
  {
    id: 'verify_platinum',
    title: 'Senior Auditor',
    description: 'Verified 60 community issues creating high-confidence district data.',
    icon: 'verify_platinum',
    category: 'verification',
    requiredCount: 60,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Senior Auditor',
  },
  {
    id: 'verify_diamond',
    title: 'Supreme Validator',
    description: 'Validated 100 on-site hazard reports across the metropolitan zone.',
    icon: 'verify_diamond',
    category: 'verification',
    requiredCount: 100,
    currentCount: 0,
    isUnlocked: false,
    tier: 'diamond',
    rewardTitle: 'Supreme Validator',
  },
  {
    id: 'double_check',
    title: 'Urgency Sentinel',
    description: 'Escalated 3 rapidly deteriorating hazards to high urgency.',
    icon: 'double_check',
    category: 'verification',
    requiredCount: 3,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Urgency Sentinel',
  },
  {
    id: 'hawk_eye',
    title: 'Hawk Eye',
    description: 'Verified hazards across 5 distinct geographic sectors.',
    icon: 'hawk_eye',
    category: 'verification',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Hawk Eye',
  },
  {
    id: 'peer_trusted',
    title: 'Trusted Peer',
    description: 'Received 10 matching confirmations from fellow citizens.',
    icon: 'peer_trusted',
    category: 'verification',
    requiredCount: 10,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Trusted Peer',
  },

  // ==========================================
  // 6. 🛠️ RESTORATION & PROOF (6 BADGES)
  // ==========================================
  {
    id: 'fix_witness',
    title: 'Repair Witness',
    description: 'Uploaded your first on-site photo proof confirming a repaired hazard.',
    icon: 'fix_witness',
    category: 'resolution',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Repair Witness',
  },
  {
    id: 'fix_agent',
    title: 'Restoration Agent',
    description: 'Verified 5 completed repairs with live camera photo proof.',
    icon: 'fix_agent',
    category: 'resolution',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Restoration Agent',
  },
  {
    id: 'fix_champion',
    title: 'Restoration Champion',
    description: 'Confirmed 15 road restoration milestones for the community.',
    icon: 'fix_champion',
    category: 'resolution',
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Restoration Champion',
  },
  {
    id: 'fix_legend',
    title: 'City Restorer',
    description: 'Verified 30 completed municipal repairs with visual evidence.',
    icon: 'fix_legend',
    category: 'resolution',
    requiredCount: 30,
    currentCount: 0,
    isUnlocked: false,
    tier: 'diamond',
    rewardTitle: 'City Restorer',
  },
  {
    id: 'before_after',
    title: 'Proof Master',
    description: 'Verified resolution photo match on a high-severity critical hazard.',
    icon: 'before_after',
    category: 'resolution',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Proof Master',
  },
  {
    id: 'zero_hazard',
    title: 'Safe Sector Hero',
    description: 'Helped resolve and verify all logged hazards in a 1km neighbourhood zone.',
    icon: 'zero_hazard',
    category: 'resolution',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'master',
    rewardTitle: 'Safe Sector Hero',
  },

  // ==========================================
  // 7. ⚡ STREAKS & CONSISTENCY (8 BADGES)
  // ==========================================
  {
    id: 'streak_3',
    title: '3-Day Spark',
    description: 'Maintained an active reporting and verification streak for 3 days.',
    icon: 'streak_3',
    category: 'streak',
    requiredCount: 3,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Momentum Scout',
  },
  {
    id: 'streak_7',
    title: '7-Day Flame',
    description: 'Maintained a consecutive 7-day daily activity streak.',
    icon: 'streak_7',
    category: 'streak',
    requiredCount: 7,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Flame Scout',
  },
  {
    id: 'streak_14',
    title: '2-Week Fortitude',
    description: 'Achieved a two-week continuous daily contribution streak.',
    icon: 'streak_14',
    category: 'streak',
    requiredCount: 14,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Fortitude Scout',
  },
  {
    id: 'streak_30',
    title: 'Monthly Champion',
    description: 'Incredible dedication: 30 consecutive days of active civic engagement.',
    icon: 'streak_30',
    category: 'streak',
    requiredCount: 30,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Monthly Champion',
  },
  {
    id: 'streak_60',
    title: '60-Day Iron Scout',
    description: 'Iron discipline: 60 consecutive days of roadway safety activity.',
    icon: 'streak_60',
    category: 'streak',
    requiredCount: 60,
    currentCount: 0,
    isUnlocked: false,
    tier: 'diamond',
    rewardTitle: 'Iron Scout',
  },
  {
    id: 'streak_100',
    title: '100-Day Centurion',
    description: 'Ultimate civic commitment: 100 consecutive days on duty.',
    icon: 'streak_100',
    category: 'streak',
    requiredCount: 100,
    currentCount: 0,
    isUnlocked: false,
    tier: 'master',
    rewardTitle: 'Centurion Scout',
  },
  {
    id: 'weekend_hero',
    title: 'Weekend Hero',
    description: 'Reported and verified hazards during weekend morning scouts.',
    icon: 'weekend_hero',
    category: 'streak',
    requiredCount: 2,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Weekend Hero',
  },
  {
    id: 'holiday_keeper',
    title: 'Holiday Keeper',
    description: 'Stayed active on public holidays to keep travellers safe.',
    icon: 'holiday_keeper',
    category: 'streak',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Holiday Keeper',
  },

  // ==========================================
  // 8. 🏆 MILESTONE CENTURY HEXAGONS & AI (6 BADGES)
  // ==========================================
  {
    id: 'milestone_10',
    title: '10 Club Hexagon',
    description: 'Reached 10 total validated roadway submissions.',
    icon: 'milestone_10',
    category: 'milestones',
    requiredCount: 10,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: '10 Club Member',
  },
  {
    id: 'milestone_25',
    title: '25 Club Hexagon',
    description: 'Quarter-century milestone: 25 total validated hazard reports.',
    icon: 'milestone_25',
    category: 'milestones',
    requiredCount: 25,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: '25 Club Member',
  },
  {
    id: 'milestone_50',
    title: '50 Silver Hexagon',
    description: 'Half-century milestone: 50 total validated hazard submissions.',
    icon: 'milestone_50',
    category: 'milestones',
    requiredCount: 50,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: '50 Silver Veteran',
  },
  {
    id: 'milestone_100',
    title: '100 Gold Century',
    description: 'Century Club: 100 total validated reports transforming city infrastructure.',
    icon: 'milestone_100',
    category: 'milestones',
    requiredCount: 100,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Century Champion',
  },
  {
    id: 'milestone_250',
    title: '250 Grandmaster Hexagon',
    description: 'Grandmaster ranking: 250 total verified civic submissions.',
    icon: 'milestone_250',
    category: 'milestones',
    requiredCount: 250,
    currentCount: 0,
    isUnlocked: false,
    tier: 'diamond',
    rewardTitle: 'Civic Grandmaster',
  },
  {
    id: 'ai_visionary',
    title: 'AI Neural Scout',
    description: 'Utilized Gemini AI Vision to automatically detect and classify 5 road hazards.',
    icon: 'ai_visionary',
    category: 'milestones',
    requiredCount: 5,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'AI Neural Scout',
  },
];
