import { CivicIssue } from '@/types/issue';
import { generateIssueTimeline } from '@/utils/priority';

// Default central reference point for CivicLens demo hub
export const DEFAULT_REGION = {
  latitude: 28.6139,
  longitude: 77.2090,
  latitudeDelta: 0.038,
  longitudeDelta: 0.038,
};

export const INITIAL_MOCK_ISSUES: CivicIssue[] = [
  {
    id: 'issue-101',
    category: 'pothole',
    description: 'Deep 2-foot wide pothole near main traffic junction. Motorcyclists constantly swerving into oncoming traffic.',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    latitude: 28.6145,
    longitude: 77.2085,
    locationName: 'Connaught Circus & Janpath Intersection',
    severity: 'high',
    status: 'active',
    reportedBy: 'user-demo-1',
    reporterName: 'Aarav Sharma',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000 * 24).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000 * 24).toISOString(),
    confirmationCount: 8,
    gettingWorseCount: 3,
    repairedVotesCount: 0,
    aiSuggestedCategory: 'pothole',
    aiConfidence: 0.96,
    priorityScore: 92,
    priorityTier: 'Critical / Urgent',
    impactFactors: ['two_wheeler_danger', 'traffic_slowdown', 'vehicle_damage'],
    roadType: 'main_road',
    trafficLevel: 'heavy',
    timeline: generateIssueTimeline({
      category: 'pothole',
      reporterName: 'Aarav Sharma',
      createdAt: '2 days ago',
      confirmationCount: 8,
      priorityScore: 92,
      status: 'active',
    }),
  },
  {
    id: 'issue-102',
    category: 'garbage',
    description: 'Overflowing community waste dumpster spilling onto pedestrian walkway and bicycle lane.',
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    latitude: 28.6250,
    longitude: 77.2210,
    locationName: 'Mandi House Circle & Sikandra Road',
    severity: 'medium',
    status: 'active',
    reportedBy: 'user-demo-2',
    reporterName: 'Priya Verma',
    createdAt: new Date(Date.now() - 1 * 3600 * 1000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000 * 24).toISOString(),
    confirmationCount: 5,
    gettingWorseCount: 1,
    repairedVotesCount: 0,
    aiSuggestedCategory: 'garbage',
    aiConfidence: 0.94,
    priorityScore: 68,
    priorityTier: 'High Priority',
    impactFactors: ['pedestrian_danger'],
    roadType: 'local_street',
    trafficLevel: 'medium',
    timeline: generateIssueTimeline({
      category: 'garbage',
      reporterName: 'Priya Verma',
      createdAt: '1 day ago',
      confirmationCount: 5,
      priorityScore: 68,
      status: 'active',
    }),
  },
  {
    id: 'issue-103',
    category: 'streetlight',
    description: 'Dual-arm street lighting pole broken at the base and dark for 3 consecutive nights. Total blackout on lane.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    latitude: 28.6040,
    longitude: 77.2010,
    locationName: 'Race Course Road & Safdarjung Junction',
    severity: 'high',
    status: 'active',
    reportedBy: 'user-demo-3',
    reporterName: 'Vikram Singh',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000 * 24).toISOString(),
    confirmationCount: 12,
    gettingWorseCount: 2,
    repairedVotesCount: 0,
    aiSuggestedCategory: 'streetlight',
    aiConfidence: 0.98,
    priorityScore: 86,
    priorityTier: 'Critical / Urgent',
    impactFactors: ['pedestrian_danger', 'two_wheeler_danger'],
    roadType: 'main_road',
    trafficLevel: 'medium',
    timeline: generateIssueTimeline({
      category: 'streetlight',
      reporterName: 'Vikram Singh',
      createdAt: '4 days ago',
      confirmationCount: 12,
      priorityScore: 86,
      status: 'active',
    }),
  },
  {
    id: 'issue-104',
    category: 'road_damage',
    description: 'Extensive spiderweb asphalt cracking and subsidence across middle lane right before subway exit.',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    latitude: 28.6280,
    longitude: 77.2040,
    locationName: 'Paharganj Bridge & Railway Flyover Ramp',
    severity: 'medium',
    status: 'active',
    reportedBy: 'user-demo-4',
    reporterName: 'Neha Gupta',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 3600 * 1000 * 24).toISOString(),
    confirmationCount: 4,
    gettingWorseCount: 0,
    repairedVotesCount: 0,
    aiSuggestedCategory: 'road_damage',
    aiConfidence: 0.89,
    priorityScore: 58,
    priorityTier: 'Moderate Priority',
    impactFactors: ['vehicle_damage', 'traffic_slowdown'],
    roadType: 'main_road',
    trafficLevel: 'heavy',
    timeline: generateIssueTimeline({
      category: 'road_damage',
      reporterName: 'Neha Gupta',
      createdAt: '3 days ago',
      confirmationCount: 4,
      priorityScore: 58,
      status: 'active',
    }),
  },
  {
    id: 'issue-105',
    category: 'pothole',
    description: 'Repaired by neighborhood community road squad. Asphalt patched and roller leveling completed.',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    latitude: 28.6080,
    longitude: 77.2190,
    locationName: 'Barakhamba Road & India Gate Outer Hexagon',
    severity: 'low',
    status: 'resolved',
    reportedBy: 'user-demo-1',
    reporterName: 'Aarav Sharma',
    createdAt: new Date(Date.now() - 7 * 3600 * 1000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000 * 24).toISOString(),
    confirmationCount: 14,
    gettingWorseCount: 0,
    repairedVotesCount: 6,
    resolvedAt: new Date(Date.now() - 1 * 3600 * 1000 * 24).toISOString(),
    resolvedBy: 'citizen-scout-9',
    aiSuggestedCategory: 'pothole',
    aiConfidence: 0.95,
    priorityScore: 20,
    priorityTier: 'Low Priority',
    impactFactors: [],
    roadType: 'main_road',
    trafficLevel: 'medium',
    timeline: generateIssueTimeline({
      category: 'pothole',
      reporterName: 'Aarav Sharma',
      createdAt: '7 days ago',
      confirmationCount: 14,
      status: 'resolved',
      resolvedAt: 'Yesterday',
    }),
  },
];
